Repository EliasBN/todo, pull requests merged in 2019-06, with the labels that each got.

#6 Updating experimental branch with new sorting functions for todoITEMS.
  .DS_Store
  .gitignore
  README.md
  frontend/README.md
  frontend/src/components/Homepage.js
  frontend/src/components/Routes.js
  frontend/src/containers/Login/Login.js
  frontend/src/containers/MyTodo/MyTodo.js
  frontend/src/containers/MyTodo/components/MyTodoItem.js
  frontend/src/containers/TODO/Todo.js
  frontend/src/containers/TODO/components/TodoItem.js
  frontend/src/functions/helpers.js
  guides/backend.md
  guides/frontend.md
Labels: Fix, enhancement

#7 Forgot to delete imports - should work run now
  purefrontend/frontend/src/components/Routes.js
Labels: Fix

#19 Moving from development into master
  .gitignore
  .sequelizerc
  README.md
  backend/.DS_Store
  backend/LICENSE
  backend/app.js
  backend/bin/www
  backend/package-lock.json
  backend/package.json
  backend/server/config/config.json
  backend/server/controllers/index.js
  backend/server/controllers/todoitems.js
  backend/server/controllers/todos.js
  backend/server/migrations/20190307170043-create-todo.js
  backend/server/migrations/20190307170209-create-todo-item.js
  backend/server/models/index.js
  backend/server/models/todo.js
  backend/server/models/todoitem.js
  backend/server/routes/index.js
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/Button.js
  frontend/src/components/Checkbox.js
  frontend/src/components/Homepage.js
  frontend/src/components/Routes.js
  frontend/src/components/TextArea.js
  frontend/src/components/TextInput.js
  frontend/src/components/notFound.js
  frontend/src/containers/Login/Login.js
  frontend/src/containers/MyTodo/MyTodo.js
  frontend/src/containers/MyTodo/components/FormDialog.js
  frontend/src/containers/MyTodo/components/InputForm.js
  frontend/src/containers/MyTodo/components/MyTodoItem.js
  frontend/src/containers/MyTodo/components/MyTodoList.js
  frontend/src/containers/MyTodo/components/Popup.js
  frontend/src/containers/TODO/Todo.js
  frontend/src/containers/TODO/components/InputForm.js
  frontend/src/containers/TODO/components/TodoItem.js
  frontend/src/containers/TODO/components/TodoList.js
  frontend/src/functions/helpers.js
  frontend/src/index.js
  frontend/src/serviceWorker.js
  guides/backend.md
  guides/frontend.md
Labels: enhancement
